export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';
export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const SET_DAILY_WEATHER = 'SET_DAILY_WEATHER';
export const SET_CITY = 'SET_CITY';